### ISSUE TITLE
Bug when run process_dataset.py

### ISSUE THREAD

**Issue by henrycjh** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#3]
After convertion of the bvh file, there is an error (shown below), and it is because the BatchMirror class is in src.Datasets.augmentation, not src.Datasets.BatchProcessor.

```
Traceback (most recent call last):
  File "process_dataset.py", line 173, in <module>
    splitStyle100TrainTestSet()
  File "process_dataset.py", line 151, in splitStyle100TrainTestSet
    style_loader.split_from_binary()
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/Style100Processor.py", line 225, in split_from_binary
    from src.Datasets.BatchProcessor import BatchMirror
```

**Comment by henrycjh** [comment]
After solving this error, another error occurs when I run `python process_dataset.py --train_phase_model`, shown below:
```
Traceback (most recent call last):
  File "process_dataset.py", line 175, in <module>
    processDeepPhaseForStyle100(62,2)
  File "process_dataset.py", line 145, in processDeepPhaseForStyle100
    style_loader.process_from_binary()
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/Style100Processor.py", line 273, in process_from_binary
    self.train_dict = self._process_dataset(self.train_motions)
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/Style100Processor.py", line 293, in _process_dataset
    train_set = self.processor({"offsets": o, "hip_pos": h, "quats": q}, self.skeleton, self)
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/DeepPhaseDataModule.py", line 48, in __call__
    gv = self.transform_single(offsets, hip_pos,quats, skeleton)
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/DeepPhaseDataModule.py", line 29, in transform_single
    dict = self.process(gq.unsqueeze(0),gp.unsqueeze(0))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/BatchProcessor.py", line 50, in forward
    ref_vector = torch.cross(global_positions[...,5:6,:]-global_positions[...,1:2,:],torch.tensor([0,1,0],dtype=global_positions.dtype,device=global_positions.device),dim=-1)
RuntimeError: inconsistent tensors dimensions input: 5 other: 1
```
It seems that torch.cross() requires the two inputs to be same dimensions and same size.

**Comment by yuyujunjun** [comment]
Thank you, in some pytorch version it is indeed a problem. 
Change the ref_vector to :
```ref_vector = torch.cross(global_positions[...,5:6,:]-global_positions[...,1:2,:],torch.tensor([0,1,0],dtype=global_positions.dtype,device=global_positions.device).expand(global_positions[...,0:1,:].shape),dim=-1)```
